version: "3"

services:
  backend:
    image: gioe1996/test-erpnext:latest
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  configurator:
    image: gioe1996/test-erpnext:latest
    deploy:
      restart_policy:
        condition: none
    entrypoint:
      - bash
      - -c
    # add redis_socketio for backward compatibility
    command:
      - >
        ls -1 apps > sites/apps.txt;
        bench set-config -g db_host $$DB_HOST;
        bench set-config -gp db_port $$DB_PORT;
        bench set-config -g redis_cache "redis://$$REDIS_CACHE";
        bench set-config -g redis_queue "redis://$$REDIS_QUEUE";
        bench set-config -g redis_socketio "redis://$$REDIS_QUEUE";
        bench set-config -gp socketio_port $$SOCKETIO_PORT;
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
      SOCKETIO_PORT: "9000"
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  create-site:
    command: ["bash"]
    image: gioe1996/test-erpnext:latest
    deploy:
      restart_policy:
        condition: none
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    entrypoint:
      - bash
      - -c
    command:
      - >
        set -x && 
        wait-for-it -t 120 db:3306 &&
        wait-for-it -t 120 redis-cache:6379 &&
        wait-for-it -t 120 redis-queue:6379 &&
        export start=`date +%s` &&
        until [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".db_host // empty"` ]] && \
          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_cache // empty"` ]] && \
          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_queue // empty"` ]];
        do
          echo "Waiting for sites/common_site_config.json to be created" &&
          sleep 5 &&
          if (( `date +%s`-start > 120 )); then
            echo "could not find sites/common_site_config.json with required keys" &&
            exit 1
          fi
        done &&
        echo "sites/common_site_config.json found" &&
        bench new-site --no-mariadb-socket --admin-password=admin --db-root-password=admin --install-app erpnext --set-default test.orisi.rako.ge &&
        echo 'y' | bench get-app --branch version-15 hrms https://github.com/frappe/hrms &&
        echo 'y' | bench get-app --branch version-15 payments https://github.com/frappe/payments &&
        echo 'y' | bench get-app --branch version-15 webshop https://github.com/frappe/webshop &&
        echo 'y' | bench get-app --branch main helpdesk https://github.com/frappe/helpdesk &&
        echo 'y' | bench get-app --branch main ecomerce_integrations https://github.com/frappe/ecommerce_integrations &&
        #echo 'y' | bench get-app --branch develop raven https://github.com/The-Commit-Company/Raven && #did not auto-download and created some issues
        echo 'y' | bench get-app --branch master translator https://github.com/frappe/translator && #did not download but I dont even think I need this?
        echo 'y' | bench get-app --branch master wiki https://github.com/frappe/wiki && #did not download but it got installed
        # additional bench get-app commands if any...
        bench --site test.orisi.rako.ge install-app hrms &&
        bench --site test.orisi.rako.ge install-app payments &&
        bench --site test.orisi.rako.ge install-app webshop &&
        bench --site test.orisi.rako.ge install-app helpdesk &&
        bench --site test.orisi.rako.ge install-app ecommerce_integrations &&
        bench --site test.orisi.rako.ge install-app raven && #got installed BUT causing issues
        bench --site test.orisi.rako.ge install-app translator && #got installed probobly dont ened it
        bench --site test.orisi.rako.ge install-app wiki && #wiki.js is better but its different platform and will require additional backup setup so IDK
        cd ~ && git clone https://github.com/GeoCommander/frappe-app-translations.git && cd frappe-app-translations/erpnext &&
        cp ka.csv /home/frappe/frappe-bench/apps/erpnext/erpnext/translations/ &&
        cd ../frappe && cp languages.json /home/frappe/frappe-bench/apps/frappe/frappe/geo &&
        bench migrate &&
        bench build;
                
        
        #bench --site test.orisi.rako.ge install-app payments;
        #bench --site test.orisi.rako.ge migrate;
        #bench --site test.orisi.rako.ge build;
        #bench new-site --install-app websocket drive test.orisi.rako.ge; # individual test
        #bench new-site --no-mariadb-socket --admin-password=admin --db-root-password=admin --install-app lending --set-default test.orisi.rako.ge; #test with erpnext
        #bench --site test.orisi.rako.ge install-app webshop;

  db:
    image: mariadb:10.6
    healthcheck:
      test: mysqladmin ping -h localhost --password=admin
      interval: 1s
      retries: 15
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - db-data:/var/lib/mysql

  frontend:
    image: gioe1996/test-erpnext:latest
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - nginx-entrypoint.sh
    environment:
      BACKEND: backend:8000
      FRAPPE_SITE_NAME_HEADER: test.orisi.rako.ge
      SOCKETIO: websocket:9000
      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
      UPSTREAM_REAL_IP_RECURSIVE: "off"
      PROXY_READ_TIMEOUT: 120
      CLIENT_MAX_BODY_SIZE: 50m
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    ports:
      - "9999:8080"

  queue-long:
    image: gioe1996/test-erpnext:latest
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - bench
      - worker
      - --queue
      - long,default,short
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  queue-short:
    image: gioe1996/test-erpnext:latest
    deploy:
      restart_policy:
        condition: on-failure
    depends_on: ["backend"]
    command:
      - bench
      - worker
      - --queue
      - short,default
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  redis-queue:
    image: redis:6.2-alpine
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - redis-queue-data:/data

  redis-cache:
    image: redis:6.2-alpine
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - redis-cache-data:/data

  scheduler:
    image: gioe1996/test-erpnext:latest
    deploy:
      restart_policy:
        condition: on-failure
    depends_on: ["backend"]
    command:
      - bench
      - schedule
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

  websocket:
    image: gioe1996/test-erpnext:latest
    deploy:
      restart_policy:
        condition: on-failure
    command:
      - node
      - /home/frappe/frappe-bench/apps/frappe/socketio.js
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs

volumes:
  db-data:
  redis-queue-data:
  redis-cache-data:
  sites:
  logs:
